---
title: "ggplotでグループ毎の頻度ヒストグラムを隣り合わせて作成"
categories:
  - R
  - tidyverse
description: |
  group histogram by ggplot
author:
  - name: fuuuumin
    url: https://fu-om.github.io/ByTheWay/
date: 2022-01-07
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

タイトル通りにplotしようとしたら詰まったためメモ。

サンプルデータ。$x1 \sim Binom(20, 0.2)$, $x2 \sim Binom(20, 0.5)$

```{r}
library(tidyverse)
set.seed(123)
n1 <- 200
n2 <- n1 * 3
df <- tibble(type = c(rep("x1", n1), rep("x2", n2)), 
             value = c(abs(rbinom(n = n1, 20, 0.2)), abs(rbinom(n = n2, 20, 0.5))))
```

[Githubにissue](https://github.com/tidyverse/ggplot2/issues/3522)が上がっていたが、そのままだとgroup毎の頻度がずれていた。結論としては、`geom_histogram`に`binwidth`ではなく`breaks`を渡さないといけなかった。

`breaks`なし

```{r}
bw <- 2; min_val <- 0; max_val <- 20
ggplot(df, aes(x = value, y = stat(density*width), fill=type)) +
  geom_histogram(binwidth = bw, position=position_dodge()) +
  scale_x_continuous(breaks = seq(min_val, max_val, bw), limits = c(min_val, max_val), expand = c(0, 0))
```

`breaks`あり

```{r}
ggplot(df, aes(x = value, y = stat(density*width), fill=type)) +
  geom_histogram(breaks = seq(min_val, max_val, bw), position=position_dodge()) +
  scale_x_continuous(breaks = seq(min_val, max_val, bw), limits = c(min_val, max_val), expand = c(0, 0))
```

頻度表

```{r}
df %>% 
group_by(type, ints = cut_width(value, width = 2, boundary = 0)) %>% 
  summarise(n = n()) %>% 
  mutate(freq = n / sum(n)) %>% 
  select(-n) %>% 
  pivot_wider(names_from = type, values_from = freq, values_fill = 0)
```

